version: '3'

volumes:
  rippled: {}
  prometheus: {}
  grafana: {}

services:
  rippled:
    image: 'exodusmovement/rippled:1.0.1-002'
    container_name: rippled
    volumes:
      - ./rippled:/home/rippled/config/
      - rippled:/home/rippled/xrpdb/
    command: >
      --conf /home/rippled/config/rippled.cfg
      --silent
    ports:
      - 5005:5005

  rippled-exporter:
    build:
      context: ../
    container_name: rippled-exporter
    depends_on:
      - rippled
    volumes:
      - ./rippled-exporter/config.yaml:/home/node/rippled-exporter/config.yaml
    command: >
      --config config.yaml
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    depends_on:
      - rippled-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring
