{
 "title": "Rippled",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Peers versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rippled_peers{name=\"xrp1\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rippled_version{name=\"xrp1\"}"
    },
    {}
   ]
  },
  {
   "title": "Total sync",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rippled_complete_ledgers{name=\"xrp1\",topic=\"progress\"}"
    }
   ]
  },
  {
   "title": "First ledger",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rippled_complete_ledgers{name=\"xrp1\",topic=\"from\"}"
    }
   ]
  },
  {
   "title": "Most recent ledger",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rippled_complete_ledgers{name=\"xrp1\",topic=\"to\"}"
    }
   ]
  },
  {
   "title": "Total number of ledgers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rippled_complete_ledgers{name=\"xrp1\",topic=\"total\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rippled_peers{name=\"xrp1\",topic=\"all\"}",
     "legendFormat": "peers count of xrp1"
    }
   ]
  },
  {
   "title": "Base fee in drops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rippled_fee{name=\"xrp1\"}",
     "legendFormat": "xrp1 base fee in drops"
    }
   ]
  }
 ]
}